# Member 3 — Web Search Node
# Runs DuckDuckGo searches for each query generated by the Planner.
# Results are APPENDED to state (operator.add reducer in state.py),
# so previous iterations are preserved.

from langchain_community.tools import DuckDuckGoSearchResults

from state import ResearchState

search_tool = DuckDuckGoSearchResults(max_results=3)


def search_node(state: ResearchState) -> dict:
    """Run each search query and collect results."""
    queries   = state.get("search_queries", [])
    iteration = state.get("iteration", 0)

    # On loop-backs the critic may have flagged missing topics —
    # add those as extra queries so we search more specifically.
    missing = state.get("missing_topics", [])
    if missing:
        extra_queries = [f"{state['ticker']} {topic}" for topic in missing]
        queries = queries + extra_queries

    new_results = []
    for q in queries:
        try:
            result = search_tool.invoke(q)
            new_results.append(f"[Query: {q}]\n{result}")
            print(f"[Search] '{q}' — OK")
        except Exception as e:
            print(f"[Search] '{q}' — failed: {e}")

    return {
        "search_results": new_results,   # appended via operator.add
        "iteration": iteration + 1,
    }
