# Member 3 — Web Search Node
# Runs web searches for each query generated by the Planner.
# Results are APPENDED to state (operator.add reducer in state.py),
# so previous iterations are preserved.
#
# Primary backend is Tavily (proper AI-search API with a real free tier and
# predictable rate limits). If no TAVILY_API_KEY is set, or a Tavily call
# fails, we fall back to scraping DuckDuckGo so the demo still works offline.
#
# The search capability is defined as a proper LangChain @tool, which makes
# it compatible with llm.bind_tools() for fully agentic search behaviour.

import os
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FutureTimeout

from langchain_community.tools import DuckDuckGoSearchResults
from langchain_core.tools import tool

from state import ResearchState

# Per-query wall-clock timeout (seconds). A search backend can hang on a bad
# connection, which would otherwise freeze the whole pipeline.
_SEARCH_TIMEOUT = 15

_ddg = DuckDuckGoSearchResults(max_results=3)
_executor = ThreadPoolExecutor(max_workers=2)

# Build the Tavily tool once, only if a key is present.
_tavily = None
if os.getenv("TAVILY_API_KEY"):
    try:
        from langchain_tavily import TavilySearch
        _tavily = TavilySearch(max_results=3)
    except Exception as e:
        print(f"[Search] Tavily unavailable, using DuckDuckGo: {e}")


def _run_search(query: str) -> str:
    """Try Tavily first; fall back to DuckDuckGo on any failure."""
    if _tavily is not None:
        try:
            return str(_tavily.invoke({"query": query}))
        except Exception as e:
            print(f"[Search] Tavily failed ('{query}'), falling back to DDG: {e}")
    return str(_ddg.invoke(query))


@tool
def search_web(query: str) -> str:
    """Search the web for financial news, earnings, analyst reports, and market data."""
    # Run the (potentially hanging) call in a worker thread so we can
    # enforce a hard timeout — a stuck request can never freeze the app.
    future = _executor.submit(_run_search, query)
    return future.result(timeout=_SEARCH_TIMEOUT)


def search_node(state: ResearchState) -> dict:
    """Run each search query via the search_web tool and collect results."""
    queries   = state.get("search_queries", [])
    iteration = state.get("iteration", 0)

    # On loop-backs the critic may have flagged missing topics —
    # add those as extra queries so we search more specifically.
    missing = state.get("missing_topics", [])
    if missing:
        extra_queries = [f"{state['ticker']} {topic}" for topic in missing]
        queries = queries + extra_queries

    new_results = []
    for q in queries:
        try:
            result = search_web.invoke({"query": q})
            new_results.append(f"[Query: {q}]\n{result}")
            print(f"[Search] '{q}' — OK")
        except FutureTimeout:
            print(f"[Search] '{q}' — timed out after {_SEARCH_TIMEOUT}s, skipping")
        except Exception as e:
            print(f"[Search] '{q}' — failed: {e}")

    return {
        "search_results": new_results,   # appended via operator.add
        "iteration": iteration + 1,
    }
