# Member 3 — Web Search Node
# Runs DuckDuckGo searches for each query generated by the Planner.
# Results are APPENDED to state (operator.add reducer in state.py),
# so previous iterations are preserved.
#
# The search capability is defined as a proper LangChain @tool, which makes
# it compatible with llm.bind_tools() for fully agentic search behaviour.

from langchain_community.tools import DuckDuckGoSearchResults
from langchain_core.tools import tool

from state import ResearchState

_ddg = DuckDuckGoSearchResults(max_results=3)


@tool
def search_web(query: str) -> str:
    """Search the web for financial news, earnings, analyst reports, and market data."""
    return _ddg.invoke(query)


def search_node(state: ResearchState) -> dict:
    """Run each search query via the search_web tool and collect results."""
    queries   = state.get("search_queries", [])
    iteration = state.get("iteration", 0)

    # On loop-backs the critic may have flagged missing topics —
    # add those as extra queries so we search more specifically.
    missing = state.get("missing_topics", [])
    if missing:
        extra_queries = [f"{state['ticker']} {topic}" for topic in missing]
        queries = queries + extra_queries

    new_results = []
    for q in queries:
        try:
            result = search_web.invoke({"query": q})
            new_results.append(f"[Query: {q}]\n{result}")
            print(f"[Search] '{q}' — OK")
        except Exception as e:
            print(f"[Search] '{q}' — failed: {e}")

    return {
        "search_results": new_results,   # appended via operator.add
        "iteration": iteration + 1,
    }
